// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '<Your API Key>',
    appId: '1:966449037261:web:0ad2876e0b89b675ac0e84',
    messagingSenderId: '966449037261',
    projectId: 'flash-rent-07',
    authDomain: 'flash-rent-07.firebaseapp.com',
    storageBucket: 'flash-rent-07.firebasestorage.app',
    measurementId: 'G-2YBBLXFT9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '<Your API Key>',
    appId: '1:966449037261:android:fb1cc6eb8305d165ac0e84',
    messagingSenderId: '966449037261',
    projectId: 'flash-rent-07',
    storageBucket: 'flash-rent-07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '<Your API Key>',
    appId: '1:966449037261:ios:858f3366a90cdc56ac0e84',
    messagingSenderId: '966449037261',
    projectId: 'flash-rent-07',
    storageBucket: 'flash-rent-07.firebasestorage.app',
    iosBundleId: 'com.example.flashRent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '<Your API Key>',
    appId: '1:966449037261:ios:858f3366a90cdc56ac0e84',
    messagingSenderId: '966449037261',
    projectId: 'flash-rent-07',
    storageBucket: 'flash-rent-07.firebasestorage.app',
    iosBundleId: 'com.example.flashRent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '<Your API Key>',
    appId: '1:966449037261:web:0c49f86c029e853fac0e84',
    messagingSenderId: '966449037261',
    projectId: 'flash-rent-07',
    authDomain: 'flash-rent-07.firebaseapp.com',
    storageBucket: 'flash-rent-07.firebasestorage.app',
    measurementId: 'G-EX62597YQR',
  );
}
